<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_715 - 730A</name>
   <tag></tag>
   <elementGuidId>47c924ab-8bdb-4646-a1ed-49fe743be38f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.fc-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='calendarBox']/div/div[2]/div/table/tbody/tr/td/div[2]/div/div[3]/table/tbody/tr/td[3]/div/div[2]/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fc-content</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>7:15 - 7:30A</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calendarBox&quot;)/div[@class=&quot;fc fc-ltr fc-unthemed&quot;]/div[@class=&quot;fc-view-container&quot;]/div[@class=&quot;fc-view fc-timeGridWeek-view fc-timeGrid-view&quot;]/table[1]/tbody[@class=&quot;fc-body&quot;]/tr[1]/td[@class=&quot;fc-widget-content&quot;]/div[@class=&quot;fc-scroller fc-time-grid-container&quot;]/div[@class=&quot;fc-time-grid&quot;]/div[@class=&quot;fc-content-skeleton&quot;]/table[1]/tbody[1]/tr[1]/td[3]/div[@class=&quot;fc-content-col&quot;]/div[@class=&quot;fc-event-container&quot;]/a[@class=&quot;fc-time-grid-event fc-event fc-start fc-end fc-draggable fc-resizable fc-short fc-allow-mouse-resize&quot;]/div[@class=&quot;fc-content&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='calendarBox']/div/div[2]/div/table/tbody/tr/td/div[2]/div/div[3]/table/tbody/tr/td[3]/div/div[2]/a/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='all-day'])[1]/following::div[16]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat 8/1'])[1]/following::div[19]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
   </webElementXpaths>
</WebElementEntity>
