<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>s44_Person_Creates_Tasks</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>ed3dce7e-e1ce-4f05-b74e-62582ca353bb</testSuiteGuid>
   <testCaseLink>
      <guid>02e84bb6-858b-49c2-baa9-40642c29998a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s44_Person_Creates_Tasks/category_displayTaskCategory_valid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a990ffa4-105a-4bd3-bfdb-55b8a55379ef</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1d93be98-decc-4fdf-9943-5ab6fd01e8a5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s44_Person_Creates_Tasks/category_inputCategoryName_valid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>888d0be3-3887-4df6-9940-caa6cb395204</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0b503adc-0d0a-4ee4-8238-717bc6e7be1a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s44_Person_Creates_Tasks/category_inputCategoryName_invalid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2fe2bb0-b403-439a-b750-a5403f58a234</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ac1d26a0-7356-42bc-834c-dd938dbff7d2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s44_Person_Creates_Tasks/taskModal_properFieldLoadsWithDefaultValues_valid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f94116c-af85-4e70-b558-89f25bc62717</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3fb4ed3b-80e9-4d86-a717-f7ae69f3159b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s44_Person_Creates_Tasks/title_minAndMaxLength_valid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3dd35a7b-40cd-4f1d-9f70-c947243a1e1d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b04a84c0-aead-4d96-8a57-6950a18d1a80</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s44_Person_Creates_Tasks/title_minAndMaxLength_invalid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b5a1c02-daf5-4e90-ae8a-68b925e917a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>358bdee9-116d-407f-848b-bb4401f34642</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86960aef-3df9-4cf4-858a-f032d647e074</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>52cb630c-a2ef-4517-91b2-b565c0a3464f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s44_Person_Creates_Tasks/title_specialCharacters_valid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3cd72be-750e-4352-93bd-ae01aa172eb7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7a4b9cb0-adfb-4a4a-a02f-044e6915fd15</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s44_Person_Creates_Tasks/title_specialCharacters_invalid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f89770c-5b5a-436e-86c0-feac0a40dd0b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6c048df7-37e2-4fa8-a349-826e608599a3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s44_Person_Creates_Tasks/hoursEstimate_minAndMax_valid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b848ed54-c97d-4a48-8ebb-5041fd070642</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6998983-58c1-41e6-810a-743370570090</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3f3eb8db-7a0f-44a4-bbb4-5e8f69606475</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s44_Person_Creates_Tasks/hoursEstimate_minAndMax_invalid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d18f6f1-a3a8-4396-ab36-467747959741</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb758b27-bc96-4b9a-a761-9225b12759eb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f86bc041-6dbf-444f-bf97-65d429e143f8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s44_Person_Creates_Tasks/hoursEstimate_inputType_valid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00a71f20-dc34-458d-a91b-aec0f67f6a62</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>12211110-2be4-43be-863e-c540688ae305</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s44_Person_Creates_Tasks/hoursEstimate_inputType_invalid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f9cb061-f0b3-4e23-a5fe-fcf50ac3ccf1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d936075-f027-4221-8503-68027486b033</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5d43d226-da96-4c67-b0ee-b1848e339f3b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s44_Person_Creates_Tasks/submit_addingTask_valid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49287e84-4106-45ba-b437-fd2341110441</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8dfebccd-ddc3-46d8-b276-76d52fbc8d60</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>165cf3fc-7174-40e3-8932-f467dc86b8f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s44_Person_Creates_Tasks/submit_addingTask_invalid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cc2e6ca-5506-4a19-9a5e-4da37cb3c761</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>739a486c-7d8b-46ab-acd8-c8dff11b1d0d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c9e2016-0799-42fd-8a7e-f9c2aa56576a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62469e97-081a-40d9-9df7-4b6daea28713</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48ccecc3-7d28-436e-82cd-6147c7651781</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9216b08c-be89-40ed-9756-52438f1bf87f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s44_Person_Creates_Tasks/cancel_closingWindow_valid</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>53bcb3fe-50e8-491d-bfbd-db54bac953d5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s44_Person_Creates_Tasks/outsideClick_doesNotClose_valid</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
