<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>S45_Admin_Creates_Category</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>dbc261b8-5918-43c0-9ba3-f0d64eec7453</testSuiteGuid>
   <testCaseLink>
      <guid>04ca9bef-9630-4065-b652-6f222598967c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/S45_Admin_Creates_Category/category_modalDefaults</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>264217e5-72c0-4559-bebc-36705194652c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c7a483b-a693-4c6e-add9-891712cbe4d5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>45e3c79f-e796-4eec-a36c-bd3ccfaa0856</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/S45_Admin_Creates_Category/category_clickOutsideModal</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b1b2a97c-7d7c-4eaa-b1c8-368ca2094504</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/S45_Admin_Creates_Category/category_addNew_valid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be184624-44c9-4160-b2ae-f7db49bffde9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0633bdbd-fcf7-4ad3-8d4e-f00ae82584bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72c4f584-69e9-4f4c-b5b3-d8fdbe126c10</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf4a1e97-073c-4b9f-a9ea-34a4283adf94</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e710ded-eb01-4ee6-aecf-10808a433988</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a30a9cd2-932f-48d0-8fc9-f39a0d4fb84b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>32548485-81ba-4418-a37d-a0a59a25594f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/S45_Admin_Creates_Category/category_sortedParents</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2963d105-0913-4b68-a1c8-bbc4ec0d4cee</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>48de04c4-c374-4e39-8bfa-c247d1e4c660</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/S45_Admin_Creates_Category/category_addNew_invalid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f6b73f6-c489-4241-835e-120ff8fbbd1e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d29e94fa-846a-4d2c-8679-6dcfb3bb7b33</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>407d9974-5767-4d7c-904b-5c79ac7d90a0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/S45_Admin_Creates_Category/category_nameLength_valid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df94f918-351b-40f7-8bf9-22d0dc665cad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>210c1c29-94f4-432e-b42d-b6913eaec9f5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>45afe3c9-08fc-4574-ad4f-96bdedb55871</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/S45_Admin_Creates_Category/category_nameLength_invalid</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>da04afe6-3aad-4c99-add2-0aa3d9179b48</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/S45_Admin_Creates_Category/category_nameSpecialCharacters_valid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08a527b8-e225-4770-a7b9-3c2fafb03e3f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7ee41d2-766e-4b93-bccb-a3e5f95f9f95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37c02a2e-0ec3-48c9-abec-3372bbdc9c31</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fc11fe44-b4e1-42ed-9560-527c2c721267</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/S45_Admin_Creates_Category/category_nameSpecialCharacters_invalid</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>6af185f0-3f8b-45f6-8f3c-1a391d90177a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/S45_Admin_Creates_Category/category_descriptionLength_valid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59f75fcb-62b7-48b4-aa31-1e641435a2cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88cf672f-5600-4924-b2e5-2143860c8b76</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c77174cb-cde9-41c1-aaa2-84ab65c69d14</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/S45_Admin_Creates_Category/category_descriptionLength_invalid</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
