<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>s54_admin_adds_list_person</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>ca432af1-9ce1-44cf-b444-479b8fde80b0</testSuiteGuid>
   <testCaseLink>
      <guid>106fa471-9779-40b0-a89f-9a83041f6fa4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s54_Admin_adds_and_lists_people/personList_allPeopleDisplayed</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b3a148c-20f4-46f9-89e2-0401a99fa624</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4ec1f56-8bed-4c16-8147-ad6226567ca2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>82e9249d-fe04-4690-8802-080b6a409b44</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s54_Admin_adds_and_lists_people/personModal_display</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>0dac54e2-b686-4c30-9713-fa84135045c0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s54_Admin_adds_and_lists_people/PersonEmailAddress_format</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a72bac65-0248-4831-a76d-5e9df9b8d653</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec75db3a-a82c-47ea-a452-e02753d0c607</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2f55476-2fdb-4e17-93be-d7caeb069326</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>288461ca-c395-46ce-91ab-b36ea8b337b8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>612a10fb-e37b-473e-b97d-b124f898e899</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s54_Admin_adds_and_lists_people/personFirstAndLastName_format</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cdc74a70-cb4b-4b4a-b823-8b0a62b835d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25242fd8-f28d-4b3c-a0c5-38a1ae378011</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4c45b2b-3047-4acf-8037-0f59e63b1bf0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>170a657b-e525-4bef-80e1-fefe64fc487f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6ed08fb7-1881-4ae1-8290-85cfd258de87</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s54_Admin_adds_and_lists_people/personPassword_format</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fdbbee0-be79-4faa-874b-269b4f91fd36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>378c3258-92d2-4cdd-aca1-71fc99dd41b6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5c6dc926-d995-47f2-8a55-a15105ef1057</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s54_Admin_adds_and_lists_people/personEmploymentStatus_dropdownMenu</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>609ebe7b-8b07-486c-b2b9-51a970e83848</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>156f25b2-73ee-4052-9e04-7cb40cdb4efb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s54_Admin_adds_and_lists_people/personDepartment_dropdownMenu</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96911f51-6fa9-4f12-88a8-aa55f4e520c0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e67e091b-b295-4e3b-8b85-9a2e590bbba3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s54_Admin_adds_and_lists_people/personScheduledHours_format</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1817584d-62d6-4659-8321-9055af726460</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>670d51c2-5a27-4e08-bf57-ac339178e76b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8092b7b8-e8b9-4dd4-a2b9-28e7e45f8567</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s54_Admin_adds_and_lists_people/addPersonModal_submitButton</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>cd5e7d05-7660-4a80-aea0-b3d76a7a5903</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s54_Admin_adds_and_lists_people/personModal_resetData</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
