<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>s58_category_filter_by_type</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>037b09fe-7e40-4cde-aee5-df7a863a4922</testSuiteGuid>
   <testCaseLink>
      <guid>8a7415b0-df1c-4281-9e26-00a9c2607e7e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s58_filter_category_by_type/taskCategory_modalDefaultValues</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6c20464-5007-4fa1-9ecc-3c55af406c9c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36b7de44-8ad0-4c23-8eb4-b281770878cf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f53adc77-be64-4930-8e09-01b7f0457e9e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s58_filter_category_by_type/taskCategory_createTaskCategory_populatedParent</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a094b64-3fb1-41de-8fc0-83d0ec7b03a1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a525498e-ee56-4200-a80a-409a97bb3127</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e9b0956-3184-49ca-8379-100dc6767a82</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11ea5bac-203c-48af-b36d-7a6881bdb735</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a74798e-8a16-45e0-b0e0-bae4cdaa3ba4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de931e06-d4ff-4814-b367-ff64f4f7f068</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17d1b597-8492-4f6b-818f-9455f88a6c40</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>84c337e0-bfd1-4298-afd3-850985ea65ca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s58_filter_category_by_type/taskCategory_createTaskCategory_emptyParent</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>271adccf-491b-4395-b73c-61caa19fd247</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52ea0478-efbe-4591-b0f1-190d4c21a63b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c67d4b42-58b2-4821-9e1d-2fd2fc81022b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>163bd8fc-0137-4358-afc6-ca8ff44039cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>000fdeff-748a-4bb5-87ad-81a88de142af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1e26228-47c0-4de1-b20d-c39b4fa24d70</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3df2cccd-9925-4ad4-b126-55c05e431cca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0ea86494-1d1d-4ff4-9c5b-2862086cb25d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s58_filter_category_by_type/personCategory_modalDefaultValues</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31ff63e1-7f7f-445f-bad8-9e37c559e492</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01149183-a058-454f-a91f-85c0fb626f23</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0ae64c17-5a69-4d77-9350-f126367e13b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s58_filter_category_by_type/personCategory_createPersonCategory_emptyParent</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45dfabce-87ee-4654-84ef-0c4f2791cf86</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8a755db-70ac-4fc4-a32c-f62de6bbc6e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0bd4e5e0-e3a2-4ab5-b548-811b589730e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45c9f879-7492-45b8-80a8-c69d67a46a6e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b37b276-f182-497b-9aa9-cd39474470d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96bcdf51-76a7-4612-92b0-df19c38f2353</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>459a46cc-e957-4f72-be6b-bb1b5621849b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8bd76eef-a14b-41df-a356-924bf0722f32</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s58_filter_category_by_type/personCategory_createPersonCategory_populatedParent</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ece7de4e-e07d-4f53-ade8-ad5216874769</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15cc7b14-8a18-4fcd-95fd-0f806b3c2743</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d52d73d0-b6e9-47f8-9200-3e4af8e92f3f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65e9d7a1-8e0a-4f3e-bd5c-ce8b20138050</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e071bd5-cfd0-4793-980f-a13542c5c11e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a80917ba-f8de-4f1d-973b-1736a64b3156</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8dc8a2fe-1a7c-4ba1-94c5-1422eec5d4f8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>beb91cd0-dfdc-43d1-873b-b44db93bc438</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s58_filter_category_by_type/createTask_onlyTaskCategories</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6593d82-856c-48cf-82a5-bb716711572b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
