<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>s83_edit_category</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>8afab4b4-b7f5-48c3-aca8-f690be63d47a</testSuiteGuid>
   <testCaseLink>
      <guid>c1c42541-b3d0-43fd-a529-6e6ce5903ca9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/s83_edit_category/admin_view_workassignment_table</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5cd05ce-2f82-4bfd-be52-1dac5da97b5a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0580559d-3bf1-4a59-a699-b14908235714</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7c38fcb-ee92-45fc-90ff-80d497dd7e4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>772b9b44-7a85-450d-8e53-029f09bc9e3a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a37b3637-d519-4e08-8bca-5b0cfcfeea89</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb753823-c6eb-49ff-9d06-4e3e2d8f18b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07651a05-7843-45e2-a710-2d3ded699080</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>907dd7a6-bc76-477b-8540-62bd8e685303</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a93684c5-d077-48b0-bbd3-185766462a3f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/s83_edit_category/admin_view_editCategoryModal</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1e0839c7-f212-4efe-aa5f-be1215643054</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/s83_edit_category/admin_edit_workassignment_item_valid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be184624-44c9-4160-b2ae-f7db49bffde9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0633bdbd-fcf7-4ad3-8d4e-f00ae82584bd</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
