<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>record4_Jan9_Conference</name>
   <tag></tag>
   <elementGuidId>78321e92-4268-4de1-9791-e9afbefff6b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='calendarBox']/div/div[2]/div/table/tbody/tr/td/div[2]/div/div[3]/table/tbody/tr/td[6]/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fc-time-grid-event fc-event fc-not-start fc-not-end fc-allow-mouse-resize</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Conference</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calendarBox&quot;)/div[@class=&quot;fc fc-ltr fc-unthemed&quot;]/div[@class=&quot;fc-view-container&quot;]/div[@class=&quot;fc-view fc-timeGridWeek-view fc-timeGrid-view&quot;]/table[1]/tbody[@class=&quot;fc-body&quot;]/tr[1]/td[@class=&quot;fc-widget-content&quot;]/div[@class=&quot;fc-scroller fc-time-grid-container&quot;]/div[@class=&quot;fc-time-grid&quot;]/div[@class=&quot;fc-content-skeleton&quot;]/table[1]/tbody[1]/tr[1]/td[6]/div[@class=&quot;fc-content-col&quot;]/div[@class=&quot;fc-event-container&quot;]/a[@class=&quot;fc-time-grid-event fc-event fc-not-start fc-not-end fc-allow-mouse-resize&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='calendarBox']/div/div[2]/div/table/tbody/tr/td/div[2]/div/div[3]/table/tbody/tr/td[6]/div/div[2]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Conference'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meetings'])[1]/following::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Conference'])[3]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div/div[2]/a</value>
   </webElementXpaths>
</WebElementEntity>
