<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>editRecord_decreaseButton</name>
   <tag></tag>
   <elementGuidId>1f91fe9f-ad5a-428d-ad34-63d517f4ef11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@aria-controls, 'spinbutton_hours_') and @aria-label = 'Decrement']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>spinbutton_hours_</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Decrement</value>
   </webElementProperties>
</WebElementEntity>
