<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_taskList</name>
   <tag></tag>
   <elementGuidId>1fd1e027-baa2-40c0-9694-fae985b206f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='itemList']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'itemList' and (text() = concat(' A  B  C  D  Development  E  F  G  H  Here is another long task name, but in actual words and not just M' , &quot;'&quot; , 's
  I  J  K  L  M  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM  N  O  P  Plumbing  Q  R  S  T  Teaching  U  V  W  X  Y  Z  Z  Z ') or . = concat(' A  B  C  D  Development  E  F  G  H  Here is another long task name, but in actual words and not just M' , &quot;'&quot; , 's
  I  J  K  L  M  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM  N  O  P  Plumbing  Q  R  S  T  Teaching  U  V  W  X  Y  Z  Z  Z '))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>itemList</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> A  B  C  D  Development  E  F  G  H  Here is another long task name, but in actual words and not just M's
  I  J  K  L  M  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM  N  O  P  Plumbing  Q  R  S  T  Teaching  U  V  W  X  Y  Z  Z  Z </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itemList&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='itemList']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='taskList']/ul</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul</value>
   </webElementXpaths>
</WebElementEntity>
